import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/themeContext";
import ThemeToggle from "@/components/ThemeToggle";

// Fuente principal de VS Code (similar a Segoe UI)
const vsCodeFont = Inter({
  variable: "--font-vscode-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

// Fuente monospace como VS Code
const vsCodeMono = Inter({
  variable: "--font-vscode-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="w-full h-full m-0 p-0">
      <body
        className={`${vsCodeFont.variable} ${vsCodeMono.variable} antialiased bg-background text-foreground transition-colors duration-200 w-full h-full m-0 p-0`}
      >
        <ThemeProvider>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}